unjs/jiti

- src/jiti.ts
v8-compile-cache has been imported from https://github.com/nuxt-contrib/jiti/blob/da34753d54e4bc726bb354dcbd77b4f3d7f7e0a0/lib/index.js#L9 , so I guess we can remove the it from jiti.js
> fix: remove duplicate v8-compile-cache

- src/babel.ts
Without the spread the following error will be logged:
```
[jiti] Error: .plugins[4][1] must be an object, false, or undefined
```
> fix: spread when pushing babel plugins from transformOptions

- package.json
- src/babel.ts
- src/jiti.ts
- src/plugins/babel-plugin-transform-import-meta.ts
- yarn.lock
Previously we were replacing `import.meta.url` with `require('url').pathToFileURL(__filename).toString()`. This was of course fine unless it was a native ESM file which was _polyfilling_ `__filename`, `require`, etc., in which case something like this was generated:
```js
const _require2 = (0, _module.createRequire)(_require2('url').pathToFileURL(_filename).toString());
```
... which would of course fail.
Ideally we'd like not to transpile native ESM, but this does fix the issue by inlining the actual filename rather than a `require` call, and it gracefully falls back to previous behaviour if the filename isn't present.
> fix: use inlined import meta plugin to inject url

- README.md
After migration to pnpm (https://github.com/unjs/jiti/pull/69) readme wasn't update
> chore: update development section

- src/jiti.ts
Without these changes, jiti is treating `.mts` files as non-modules. Probably should add support for `.cts`, too, but I don't have a test-case for it.
> feat: add support for `.mts`

- src/jiti.ts
Jiti internally works with CJS and using MJS build is costly with non native transforms and can lead to issues. 
When a package both cjs and esm exports (most of the unjs packages), jiti should prefer cjs first as is native. However if exports condition (key order matters) is `{ types, import, require }` we first match `import`. Using two condition sets fixes the issue.
> fix: prefer require condition first in esm resolve mode

- package.json
- src/jiti.ts
- test/fixtures/circular/index.js
resolves https://github.com/unjs/jiti/issues/124
resolves https://github.com/unjs/c12/issues/58
When `requireCache` is disabled, we still need an object to track circular dependencies. The new object will be passed by `jiti` calls but in same session and invalidated after tree evaluation.
> fix: use inline require cache to avoid circular dependencies

- src/jiti.ts
- src/utils.ts
- test/utils.test.ts
Resolves #120
Workaround for pnpm setting an incorrect `TMPDIR`. See https://github.com/pnpm/pnpm/issues/6140
Thinking about it a bit more I worry that introducing this workaround also prevents people from making use of their custom `TMPDIR` - if there is one. I think that more people run `nuxt prepare` using pnpm in the respective hook, though, than people set `TMPDIR` themself. So I also added that `JITI_TMPDIR_KEEP` can be set to a truthy value to disable this workaround for people who'd like to keep their `TMPDIR`.
> fix: workaround for pnpm and `TMPDIR`

- src/jiti.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/typescript/index.ts
> feat: allow resolving `.ts` files with `.js` extension

- src/babel.ts
- src/plugins/import-meta-env.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/env/index.ts
resolves #127. I have used a fork of `@import-meta-env/babel` as it was depending on dotenv library. Also we needed simple `process.env` accessor. would be happy to move to upstream if exports similar transform options.
> feat: support `import.meta.env`

- src/jiti.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/circular/a.js
- test/fixtures/circular/b.js
- test/fixtures/circular/c.js
- test/fixtures/circular/index.js
Resolves #141
An extension of #125 to keep a shared cache from (main) parent and children while evaluating. This solves handling nested circular dependencie
> fix: handle nested circular dependencies

- .eslintignore
- src/jiti.ts
- test/__snapshots__/fixtures.test.ts.snap
#137
Rework of #139, great idea by @hairyf to expose internal eval function to eval any code
`Co-Authored-By: Mr.Mao <951416545@qq.com>`
> feat: expose `jiti.evalModule`

- src/plugins/import-meta-env.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/env/index.ts
Currently, we support `import.meta.env.foobar` by replacing AST to `process.env.foobar` but using `import.meta.env` itself was not possible and could possibly make issues like cannot use import outside of a module.
This PR also adds support for `import.meta.env?` with optional chaining, increases type safety and simplifies code.
> fix: support `import.meta.env` and `import.meta.env?.prop`

- src/jiti.ts
related to #32
It should be the very first step to have an async import function for ESM, which we could improve the implemtation later. Unblocks #158
> feat: add `jiti.import` function for async import

- README.md
Hey 👋 
This is just a small update for the bundlephobia link, because right now it opens the page for h3.
> docs: update bundlephobia link

- bin/jiti.js
- eslint.config.mjs
- src/jiti.ts
- src/types.ts
- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/bun.test.ts
- test/fixtures.test.ts
- test/fixtures/async/index.js
- test/fixtures/json/index.ts
- test/fixtures/native/index.js
- test/fixtures/top-level-await/async.mjs
- test/fixtures/top-level-await/index.ts
- test/fixtures/top-level-await/sub.ts
This PR supports basic [top level await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await) support via `jiti.import()` and `jiti <path>` CLI.
Implementation is fairly basic and adds support by wrapping the module into an `async function` instead of `function` that Node.js does.
In order to allow chained usage, since jiti transforms all imports to require internally, we replace ` = require(` patterns to ` = await require` in async contexts to make sure they are resolved. (this is more of a workaround but better than not having it!)
> feat: basic top-level await support

- src/cache.ts
- src/esm.ts
- src/eval.ts
- src/jiti.ts
- src/require.ts
- src/resolve.ts
- src/transform.ts
- src/types.ts
- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures.test.ts
- test/utils.test.ts
This PR splits jiti logic into more maintainable logical utils sharing a single context per instance.
As a result of this PR adds a few more **eager** computes on context which later could be converted to lazy initialized but reducing the amount of closure creations should help save more memory, especially with long-chain imports.
> refactor: split logic

- src/jiti.ts
This PR fixes a race condition that when importing the same `id` in parallel from several places (using `await import()`) the jiti was picking the (still) evaluating module without valid exports.
---
Context: Found it while investigating https://github.com/nuxt/nuxt/pull/27479, however this issue is just likely simply revealed with other perf improvements that increased the chance of this race.
>  fix: use internal cached modules only if loaded

- src/jiti.ts
rework of #245
detect cache race conditions while still handling circular resolution (when parent is not in loaded state)
> fix: use internal cached modules only if loaded

- package.json
- pnpm-lock.yaml
- src/babel.ts
- src/eval.ts
- src/options.ts
- src/transform.ts
- src/types.ts
- src/utils.ts
This PR removed jiti support for Node.js 12 without bullish coalescing operator and optional chaining syntax support for jiti v2
> refactor: remove legacy node syntax polyfills

- README.md
- lib/types.d.ts
- src/cache.ts
- src/eval.ts
- src/jiti.ts
- src/options.ts
- src/require.ts
- test/bun.test.ts
`cache` / `requireCache` options where confusing in previous versions of jiti and often the perf benefits of disk cache was being missed because usages was disabling fs caching wrongly assuming it stops HMR support.
Config deprecations: 
- `cache` ~> `fsCache`
- `requireCache` ~> `moduleCache`
This PR includes some other cache-related minor changes.
> refactor: use more clear `fsCache` and `moduleCache` options

- src/eval.ts
- src/jiti.ts
jiti creates a new instance when evaluating nested modules.
Some operations can be avoided and this PR avoids cache + option resolution. (more could be done but needs more refactor!)
> perf: reduce overhead of sub jiti instances

- lib/jiti-hooks.mjs
- lib/types.d.ts
- src/jiti.ts
- src/require.ts
- src/resolve.ts
- src/types.ts
Allow custom resolve options to be passed + common usecase of try import (if module exists)
> feat: allow `try` and other resolve options for `import`/`esmResolve`

- package.json
- pnpm-lock.yaml
- test/fixtures.test.ts
Replaces `execa` with `tinyexec`, a much lighter alternative.
This should be equivalent since we only use the basics of either library.
(part of the ongoing ecosystem cleanup effort)
> chore: replace exec logic in test fixtures

- lib/jiti-native.mjs
- lib/jiti-register-native.mjs
- package.json
- test/bun-native.test.ts
- vitest.config.ts
this adds a new `jiti/native` subpath export that for deno/bun/[unknown] export conditions except `node`, uses a passthrough implementation. it can be mainly useful for when we mainly require a functional `jiti.import` for typescript files without specific options.
> feat: `jiti/native` export

- package.json
Updating #289 
This PR always uses ESM import syntax for `jiti/native` (also for `node` condition) for a consistent behavior. This way we can safely use it as an **alias** for compatibility.
> refactor: always use native impl for `jiti/native`

- README.md
- lib/types.d.ts
- src/options.ts
- src/require.ts
This PR renames `experimentalBun` option to `tryNative`. I tried to test it against Deno but the lastest 1.46.3 still has issues with CJS support. 
Users of jiti can opt-in to try-native with this new agnostic option.
> refactor: rename `experimentalBun` to `tryNative`

- lib/jiti-native.mjs
- src/utils.ts
When testing, it's possible that the `instanceof URL` test does not succeed. 
Discovered/reproducible via https://github.com/nuxt/ecosystem-ci/actions/runs/10953460888/job/30413781016.
I will see if I can create a minimal reproduction - there are several layers of nesting in the more complex reproduction, but raising in case this seems good to you (and I can confirm it does resolve the issue) or you have an idea where to look further.
> fix: handle global url instance mismatch

- src/require.ts
- src/utils.ts
- test/bun.test.ts
- test/fixtures/data-uri/index.ts
- test/native/bun.test.ts
- test/native/deno.test.ts
- test/native/node.test.ts
Resolves https://github.com/unjs/jiti/issues/207
Explicitly check for `data:` scheme and use native import to handle it.
> feat: handle `data:` imports (non-native only)

- src/eval.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/import-meta/index.ts
- test/fixtures/import-meta/package.json
Resolves #167
In the async context (`jiti.import`), we can use an alternative ESM loader using dynamic imports which is slower but increases compatibility.
(Alternatively we could directly import from cache result but it needs edge-case handling for when case is disabled and HMR support will be lost too)
> feat: eval esm modules with  fallback loader

- lib/jiti-hooks.mjs
- lib/types.d.ts
- src/eval.ts
- src/jiti.ts
- src/types.ts
Make new `jiti.esmResolve` consistent with `import.meta.resolvd`
- The second argument can be also a string (parentURL same as node.js-behind-the-flag feature)
- Return value is always `file://` string normalized with mlly.
> refactor: make `jiti.esmResolve` consistent with `import.meta.resolve`

- package.json
<details><summary><h4><b>Before</b></h4></summary>
</details>
<details><summary><h4><b>After</b></h4></summary>
</deatils>
> build: fix `/register` and `/native` subpath types for `Node10` module resolution

- lib/types.d.ts
> fix: make `TransformOptions` type strict to allow auto-complete 

- README.md
- lib/types.d.ts
- src/options.ts
- test/__snapshots__/fixtures.test.ts.snap
Today most of the cases of jiti require `interopDefault` for mixed compatibility with native ESM, npm package and also between (babel) transformed modules of jiti.
Early testing seems it be a safe (although there might be edge-cases) change and also jiti v2 has not widely-adopted yet.
> feat: enable `interopDefault` by default

- lib/jiti-cli.mjs
- test/__snapshots__/fixtures.test.ts.snap
Leverage new `module.enableCompileCache` for Node.js 22+ (more info https://github.com/nodejs/node/pull/54501)
Speedup is about %17 in Node.js v22.9.0 (Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz perf mode)
```
hyperfine --warmup 3 'node ./lib/jiti-cli.mjs test/fixtures/typescript' 'NODE_DISABLE_COMPILE_CACHE=1 node ./lib/jiti-cli.mjs test/fixtures/typescript'
```
```
Benchmark 1: node ./lib/jiti-cli.mjs test/fixtures/typescript
Time (mean ± σ):     130.3 ms ±   0.8 ms    [User: 131.3 ms, System: 18.0 ms]
Range (min … max):   128.8 ms … 131.3 ms    22 runs
Benchmark 2: NODE_DISABLE_COMPILE_CACHE=1 node ./lib/jiti-cli.mjs test/fixtures/typescript
Time (mean ± σ):     152.0 ms ±   1.1 ms    [User: 149.2 ms, System: 22.0 ms]
Range (min … max):   150.1 ms … 154.0 ms    19 runs
Summary
'node …
```
> perf(cli): enable node 22 compile cache

- README.md
- lib/types.d.ts
Use `@deprecated` annotations to encourage migrating to ESM-compatible async API.
> refactor: deprecate commonjs api

- package.json
- pnpm-lock.yaml
- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/deps/defu.ts
- test/fixtures/deps/destr.ts
- test/fixtures/deps/index.ts
- test/fixtures/deps/zod.ts
Resolves #317
With jiti [v2.0.0](https://github.com/unjs/jiti/releases/tag/v2.0.0) we have introduced native ESM import support which added a new kind of mixed export handling syntax. Early testing showed jiti v2 is broken with packages like `mime` without `interop` in mixed cases so in [v2.1.0](https://github.com/unjs/jiti/releases/tag/v2.1.0) we have enabled `interopDefault` by default to support out of the box.
Issues like #317 indicate that dependencies like `zod` will now be broken (because zod's default export is not expandable)
This PR introduces a new kind of interopDefault using a Proxy which at least covers all of our current test fixtures and can be used to cover more of similar cases if reported in the future on proxy layer instead of modify default exports.
> feat: use smarter proxy for `interopDefault`

- src/utils.ts
resolves #319 (regression of #318)
If module export is a primitive like a number of string, `in` operator can throw an error. 
Instead, we can simply make sure `mod` is an object or (extended) function. (null/undefined default is still checked in line after)
> fix(interopDefault): avoid `in` operator for primitive inputs

- src/utils.ts
- test/bun.test.ts
Simplify `interopDefault` introduced in #318
Other than simplification, this PR causes to make use of Proxy in more cases (even if there is single `default` export) for better future compatibility.
> [!IMPORTANT]
> This is another behavior change in 2.x line to align behavior better with native `import`, if default export is a primitive, it needs to be accessed with `.default`.
> refactor(interopDefault): simplify logic for default export checks

- README.md
- lib/types.d.ts
- src/jiti.ts
- test/bun.test.ts
Since the introduction of native ESM, a common pattern is that we need only the `default` export. A new `jiti.import(id, { default: true })` makes this easier.
> feat: support `jiti.import(id, {default: true})`

- src/eval.ts
Resolve https://github.com/unjs/jiti/issues/324#issuecomment-2396804333.
Seems to do the trick. Let me if know if you'd need extra tests.
> fix(eval): return fallback value

- src/plugins/babel-plugin-transform-typescript-metadata/serialize-type.ts
- src/plugins/transform-module/index.ts
- src/resolve.ts
- src/utils.ts
A little round of Knip while I was at it :)
> refactor: remove some unused exports

- lib/types.d.ts
- src/jiti.ts
- test/bun.test.ts
resolves https://github.com/unjs/jiti/issues/330
Added type support
> feat: support generic type for `jiti.import<T>`

- src/resolve.ts
Resolves #334
Interestingly, with this change tests still pass and the use case is fixed. The change covers a regular use case I think: id's ending with JS resolve to a file with TS extension. BUT I'm probably missing something here, so please verify.
Btw, what's your dev mode to set breakpoints in source code directly (without build, register etc), is it possible? I often do something like `tsx --inspect src/cli.ts` but didn't succeed to create something like this.
> fix: try to resolve `.ts` files with `.js` extension from js files

- package.json
- pnpm-lock.yaml
- src/utils.ts
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/deps/iig.ts
- test/fixtures/deps/index.ts
resolves #342
interop proxy was giving up on modules with a default export that is primitive (number, boolean, etc). Since it is not object-like to be merged.
However in cases where a native ESM module has default export, we need to preserve a proxy shape with `__esModule` hint for compact and only provide default via `.default` accessor.
This change might make regression for certain cases that **babel does not adds internal wrapper**, please report in that case.
> fix: interop modules with primitive default export

- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures.test.ts
- test/fixtures/error-runtime/index.ts
- test/fixtures/esm/test.js
Simplify verbosity in snapshots to handle more node.js slight output changes in different versions
> test: simplify snapshot tests

- src/cache.ts
> fix(cache): add `+map` suffix to fs entries when `sourceMaps` enabled

- package.json
- pnpm-lock.yaml
- rspack.config.mjs
- test/__snapshots__/fixtures.test.ts.snap
- test/fixtures/typescript/index.ts
- test/fixtures/typescript/namespace.ts
resolves https://github.com/unjs/jiti/issues/406
Revert from `rspack.SwcJsMinimizerRspackPlugin` back to `terser-webpack-plugin` due to a bundle issue. 
(This is a quick fix, more details need to be investigated)
As for the bundle size:
|`rspack.SwcJsMinimizerRspackPlugin`|`terser-webpack-plugin`|
|:-|:-|
|dist/jiti.cjs: `48,555 B`| dist/jiti.cjs: `48,382 B`|
> build: revert to `terser-webpack-plugin`
